PUT http://localhost:8080/s/shorten
Content-Type: application/x-www-form-urlencoded
Authorization: foobar

url=https://www.google.com


###
PUT http://localhost:8080/s/shorten
Content-Type: application/x-www-form-urlencoded
Authorization: foobar

url=https://www.google.com/search?q=foob


###
PUT http://localhost:8080/shorten
Content-Type: application/x-www-form-urlencoded
Authorization: foobar

url=https://www.google.com/search?q=hui


###
PUT http://localhost:8080/s/shorten
Content-Type: application/x-www-form-urlencoded
Authorization: foobar

url=https://www.google.com/search?q=hi7


###
# @no-redirect
GET http://localhost:8080/s/3
Accept: application/json
Authorization: foobar


###

PUT http://simstim.de/s/shorten
Content-Type: application/x-www-form-urlencoded
Authorization: foobar

url=https://www.google.com
###

PUT http://simstim.de/s/shorten
Content-Type: application/x-www-form-urlencoded
Authorization: foobar

url=http://simstim.de


